<?php

$title = 'Delete user';

$this->headTitle($title);
$url = $this->url('user', ['action' => 'delete', 'id' => $id]);

?>

<h1><?=$this->escapeHtml($title)?></h1>

<form action="<?php echo $url; ?>" method="post">
  <p>Are you sure that want delete user?</p>
  <div class="form-group">
    <input type="hidden" name="id" value="<?php echo $user->getId(); ?>">
    <input type="submit" class="btn btn-danger" name="del" value="Yes">
    <input type="submit" class="btn btn-default" name="del" value="No">
  </div>

</form>
